version: '3.3'

services:
  db:
    image: ./mongo
    container_name: vehicules
    port:
      - 80:84
    networks:
      - Vehicule

  locataires:
    image: ./mongo
    container_name: locataires
    port:
      - 80:81
    networks:
      - Vehicule
  
  locations:
    image: ./mongo
    container_name: locations
    port: 80:82
    networks:
      - Vehicule

  locationsValide:
    image: ./mongo
    container_name: locationsValide
    port:
      - 80:83
    networks:
      - Vehicule

networks:
  - Vehicule


  







